spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc.time.zone: UTC
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user1
    password: postgres
    driver-class-name: org.postgresql.Driver