spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc.time.zone: UTC
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: zhenya
    password: 1234
    driver-class-name: org.postgresql.Driver